import{createGame,play,undo,serialize,BLACK}from'./core.js';import{BoardRenderer}from'./renderer.js';import{AudioManager}from'./audio.js';
const $=s=>document.querySelector(s),menu=$('#menuDialog'),result=$('#resultDialog'),thinking=$('#thinking'),audio=new AudioManager;let game=createGame(),mode='cpu',difficulty='normal',human=BLACK,busy=false,requestId=0;
const worker=new Worker(new URL('./ai-worker.js',import.meta.url),{type:'module'}),renderer=new BoardRenderer($('#board'),humanMove);
function selected(name){return document.querySelector(`input[name="${name}"]:checked`).value}
function update(){renderer.setState(game);const piece=$('#turnPiece');piece.className=`mini-piece ${game.turn===1?'dark':'light'}`;$('#statusText').textContent=game.winner?'しょうぶ あり！':game.draw?'ひきわけ！':`${game.turn===1?'くろ':'しろ'} の ばん`;$('#undoBtn').disabled=busy||!game.history.length;if(game.winner||game.draw)setTimeout(showResult,650)}
function humanMove(rod){if(busy||game.winner||game.draw||(mode==='cpu'&&game.turn!==human))return;if(play(game,rod)==null)return;audio.drop();update();if(mode==='cpu'&&!game.winner&&!game.draw)cpuMove()}
function cpuMove(){busy=true;thinking.hidden=false;update();worker.postMessage({game:serialize(game),difficulty,id:++requestId})}
worker.onmessage=e=>{if(e.data.id!==requestId)return;busy=false;thinking.hidden=true;if(play(game,e.data.rod)!=null)audio.drop();update()};
function start(){mode=selected('mode');difficulty=selected('difficulty');human=Number(selected('side'));game=createGame();busy=false;thinking.hidden=true;renderer.reset();update();menu.close();audio.click();if(mode==='cpu'&&human!==BLACK)setTimeout(cpuMove,350)}
function restart(){game=createGame();busy=false;thinking.hidden=true;requestId++;update();if(result.open)result.close();if(mode==='cpu'&&human!==BLACK)setTimeout(cpuMove,250)}
function showResult(){if(result.open)return;const humanWon=game.winner===human;if(game.draw){$('#resultEmoji').textContent='🤝';$('#resultTitle').textContent='ひきわけ！';$('#resultText').textContent='さいごまで よくがんばったね！'}else{$('#resultEmoji').textContent=humanWon||mode==='local'?'🎉':'🌟';$('#resultTitle').textContent=mode==='local'?`${game.winner===1?'くろ':'しろ'} の かち！`:humanWon?'やったね！':'おしい！';$('#resultText').textContent=humanWon||mode==='local'?'4つ きれいに そろったよ！':'もう一回 やってみよう！';audio.win();confetti()}result.showModal()}
function confetti(){for(let i=0;i<55;i++){const e=document.createElement('i');e.className='confetti';e.style.left=Math.random()*100+'vw';e.style.background=`hsl(${Math.random()*360} 80% 55%)`;e.style.setProperty('--drift',(Math.random()*200-100)+'px');e.style.animationDelay=Math.random()*.5+'s';document.body.append(e);setTimeout(()=>e.remove(),2500)}}
document.querySelectorAll('input[name="mode"]').forEach(x=>x.onchange=()=>$('#cpuOptions').hidden=selected('mode')==='local');$('#startBtn').onclick=e=>{e.preventDefault();start()};$('#homeBtn').onclick=()=>{if(!menu.open)menu.showModal()};$('#newBtn').onclick=restart;$('#againBtn').onclick=e=>{e.preventDefault();restart()};$('#resultMenuBtn').onclick=()=>setTimeout(()=>menu.showModal());$('#resetViewBtn').onclick=()=>renderer.reset();$('#transparentBtn').onclick=()=>{renderer.transparent=!renderer.transparent;renderer.draw()};$('#undoBtn').onclick=()=>{if(busy)return;requestId++;thinking.hidden=true;busy=false;undo(game,mode==='cpu'&&game.history.length>=2?2:1);audio.click();update()};$('#soundBtn').onclick=()=>{$('#soundBtn').textContent=audio.toggle()?'🔊':'🔇'};$('#tutorialBtn').onclick=()=>$('#tutorialDialog').showModal();renderer.setState(game);
