import{coordOf}from'./core.js';
export class BoardRenderer{
  constructor(canvas,onPick){this.c=canvas;this.ctx=canvas.getContext('2d');this.onPick=onPick;this.yaw=-.72;this.pitch=.58;this.zoom=1;this.hover=-1;this.transparent=false;this.last=-1;this.win=[];this.drag=null;this.bind();new ResizeObserver(()=>this.draw()).observe(canvas)}
  reset(){this.yaw=-.72;this.pitch=.58;this.zoom=1;this.draw()}
  setState(game){this.game=game;this.last=game.history.at(-1)?.cell??-1;this.win=game.winningLine||[];this.draw()}
  project(x,y,z){x-=1.5;y-=1.5;z-=1.5;const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch);const a=x*cy-y*sy,b=x*sy+y*cy,c=b*cp-z*sp,d=b*sp+z*cp,s=Math.min(this.c.clientWidth,this.c.clientHeight)*.13*this.zoom;return{x:this.c.clientWidth/2+a*s,y:this.c.clientHeight*.52-c*s,depth:d,r:s*.27}}
  rods(){const a=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++){const p=this.project(x,y,2.45);a.push({rod:x+y*4,p,depth:p.depth})}return a}
  pick(px,py){let best=null;for(const q of this.rods()){const d=Math.hypot(px-q.p.x,py-q.p.y);if(d<Math.max(28,q.p.r*1.8)&&(!best||d<best.d))best={rod:q.rod,d}}return best?.rod??-1}
  bind(){const pos=e=>{const r=this.c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};this.c.addEventListener('pointerdown',e=>{this.c.setPointerCapture(e.pointerId);this.drag={...pos(e),ox:e.clientX,oy:e.clientY,moved:false}});this.c.addEventListener('pointermove',e=>{const p=pos(e);if(this.drag){const dx=e.clientX-this.drag.ox,dy=e.clientY-this.drag.oy;if(Math.abs(dx)+Math.abs(dy)>5)this.drag.moved=true;this.yaw+=dx*.008;this.pitch=Math.max(-.05,Math.min(1.35,this.pitch+dy*.006));this.drag.ox=e.clientX;this.drag.oy=e.clientY;this.draw()}else{this.hover=this.pick(p.x,p.y);this.draw()}});this.c.addEventListener('pointerup',e=>{const p=pos(e);if(this.drag&&!this.drag.moved)this.onPick(this.pick(p.x,p.y));this.drag=null});this.c.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.65,Math.min(1.55,this.zoom*(1-e.deltaY*.001)));this.draw()},{passive:false})}
  sphere(p,player,alpha=1,mark=false){const g=this.ctx.createRadialGradient(p.x-p.r*.35,p.y-p.r*.4,p.r*.08,p.x,p.y,p.r);if(player===1){g.addColorStop(0,`rgba(114,133,166,${alpha})`);g.addColorStop(.55,`rgba(34,48,75,${alpha})`);g.addColorStop(1,`rgba(9,17,33,${alpha})`)}else{g.addColorStop(0,`rgba(255,255,255,${alpha})`);g.addColorStop(.6,`rgba(230,238,245,${alpha})`);g.addColorStop(1,`rgba(155,171,190,${alpha})`)}this.ctx.beginPath();this.ctx.arc(p.x,p.y,p.r,0,Math.PI*2);this.ctx.fillStyle=g;this.ctx.fill();this.ctx.lineWidth=mark?5:player===2?2:1.5;this.ctx.strokeStyle=mark?'#ffbd27':player===2?'#64748b':'#101827';this.ctx.setLineDash(player===2?[5,3]:[]);this.ctx.stroke();this.ctx.setLineDash([])}
  draw(){const dpr=Math.min(devicePixelRatio,2),w=this.c.clientWidth,h=this.c.clientHeight;if(this.c.width!==w*dpr||this.c.height!==h*dpr){this.c.width=w*dpr;this.c.height=h*dpr}this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.clearRect(0,0,w,h);if(!this.game)return;
    const base=[this.project(-.5,-.5,-.45),this.project(3.5,-.5,-.45),this.project(3.5,3.5,-.45),this.project(-.5,3.5,-.45)];this.ctx.beginPath();base.forEach((p,i)=>i?this.ctx.lineTo(p.x,p.y):this.ctx.moveTo(p.x,p.y));this.ctx.closePath();this.ctx.fillStyle='#e7aa42';this.ctx.fill();this.ctx.lineWidth=5;this.ctx.strokeStyle='#9a6428';this.ctx.stroke();
    const objects=[];for(const q of this.rods()){const{x,y}= {x:q.rod%4,y:Math.floor(q.rod/4)},lo=this.project(x,y,-.25),hi=this.project(x,y,2.65);objects.push({depth:q.depth-1,type:'rod',lo,hi,rod:q.rod});for(let z=0;z<this.game.heights[q.rod];z++){const i=x+y*4+z*16;objects.push({depth:this.project(x,y,z).depth,type:'ball',p:this.project(x,y,z),player:this.game.cells[i],i})}if(this.game.heights[q.rod]<4&&q.rod===this.hover)objects.push({depth:this.project(x,y,this.game.heights[q.rod]).depth+.01,type:'ghost',p:this.project(x,y,this.game.heights[q.rod]),player:this.game.turn})}
    objects.sort((a,b)=>a.depth-b.depth);for(const o of objects)if(o.type==='rod'){this.ctx.beginPath();this.ctx.moveTo(o.lo.x,o.lo.y);this.ctx.lineTo(o.hi.x,o.hi.y);this.ctx.lineWidth=o.rod===this.hover?7:4;this.ctx.strokeStyle=this.game.heights[o.rod]>=4?'#9da3aa':o.rod===this.hover?'#ffd12f':'#805a35';this.ctx.stroke();this.ctx.beginPath();this.ctx.arc(o.hi.x,o.hi.y,o.rod===this.hover?8:5,0,Math.PI*2);this.ctx.fillStyle=o.rod===this.hover?'#ffe14d':'#bd8750';this.ctx.fill()}else this.sphere(o.p,o.player,o.type==='ghost'?.45:this.transparent?.67:1,o.i===this.last||this.win.includes(o.i));
    if(this.win.length){const a=this.project(...Object.values(coordOf(this.win[0]))),b=this.project(...Object.values(coordOf(this.win[3])));this.ctx.beginPath();this.ctx.moveTo(a.x,a.y);this.ctx.lineTo(b.x,b.y);this.ctx.strokeStyle='#ffcf24';this.ctx.lineWidth=9;this.ctx.lineCap='round';this.ctx.stroke()}}
}
